### ISSUE TITLE
Add "trading card game"

### ISSUE THREAD

**Issue by huhn511** [iotabots/docs#4]
Documentation Page for the Trading Card Game - https://docs.iotabots.io/tcg

### Content
- [x]  Add new section with title "Trading Card Game", by #9 
- [x]  Add Description, by #9 
- [x] Add Rulebook, by #9 
- [ ] Add Information (Sale, Background infos, etc)
- [ ] Add card list

### Graphics 
- [ ] Game Mat image
- [ ] Chart of turn steps
- [ ] Detailed battle phase chart

**Comment by JM0unir** [comment]
I created the page in [PR8](https://github.com/iotabots/docs/pull/8), but left questions about the TCG on the faq page

**Comment by JM0unir** [comment]
About the Rulebook we still need : 

- Game Mat image, 
- Chart of turn steps, 
- Detailed battle phase chart,

Also I didn't understand a rule : we get 1 Mana every turn, but Mana is emptied during the end phase ? Wouldn't that mean we always start our turn with 0 Mana ? (or maybe I'm missing something 😓)

**Comment by huhn511** [comment]
> Also I didn't understand a rule : we get 1 Mana every turn, but Mana is emptied during the end phase ? Wouldn't that mean we always start our turn with 0 Mana ? (or maybe I'm missing something 😓)

Your mana will be set to 0, just if you have more than 6 cards on the hand after you turn.
